<?php

function bartik_subtheme_preprocess_page(&$variables) {

  if (isset($variables['node'])) {
    $type = $variables['node']->getType();
    if($type == 'page') {
      $variables['#attached']['library'][] = 'bartik_subtheme/node-app';
      $variables['#attached']['library'][] = 'bartik_subtheme/build/main';
      $variables['#attached']['library'][] = 'bartik_subtheme/build/shared';
    }
  }

  $value = 'something from somewhere JWT';
  setcookie("TestCookie", $value);
}
